# Generated by Django 4.2.2 on 2023-06-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('datetime_field', models.DateTimeField()),
                ('name', models.CharField(max_length=300)),
                ('contact', models.IntegerField(max_length=10)),
            ],
        ),
    ]
